django_school/classroom/urls.py
from django.urls import include, path

from .views import classroom, students

urlpatterns = [

    
       path('home_page/', students.home_page.as_view(), name='home_page'),
       path('mots_cles/add/', students.SubjectCreateView.as_view(), name='subject_add'),
       path('domaine/add/', students.DomaineCreateView.as_view(), name='domaine_add'),
       path('type/add/', students.TypeCapteurCreateView.as_view(), name='type_add'),
       path('flyer/', students.FlyerView.as_view(), name='flyer'),
       path('profile_detail/<int:pk_1>/<int:pk_2>/', students.StudentListView.as_view(), name='student_profile'),
       path('collaboration/potentielle/<int:pk_1>/profil_projet/<int:pk_2>/', students.Potentielle_profil.as_view(), name='student_profile_projet'),
       path('expert/<int:pk_1>/', students.expert_annuaire.as_view(), name='annuaire_expert'),
       path('pdf/', students.GeneratePdf.as_view()),
       path('subscribe/', students.subscribe, name = 'subscribe'),
       path('confirmation/<int:pk_1>/<int:pk_2>/<int:pk_3>/<int:notice_id>', students.confirmation_projet, name = 'confirmation_projet'),
       path('confirmation/expert/<int:pk_1>/<int:pk_2>/<int:pk_3>/<int:notice_id>', students.confirmation_expert, name = 'confirmation_expert'),
       path('projet/public/detail/<slug:slug>', students.display_detail_public, name='projet_public'),
       path('projet/public/collaboration/<slug:slug>', students.display_detail_public_coll, name='display_detail_public_coll'),
       path('projet/public/collaboration/actu/<slug:slug>', students.display_detail_public_coll_ac, name='display_detail_public_coll_ac'),
       path('capteur/public/detail/<slug:slug>', students.display_detail_capteur_public, name='capteur_public'),
       path('espace/projet/public/detail/<slug:slug>', students.espace_public, name='espace_public'),
       path('espace/capteur/public/detail/<slug:slug>', students.espace_capteur_public, name='espace_capteur_public'),
       path('boite_a_idees', students.index, name='question_an'),
       path('question/<int:qid>/<slug:qslug>', students.viewquestion),
       path('ask-question', students.askquestion, name='ask_question'),
       path('ajax-answer-question', students.ajaxanswerquestion),
       path('CapMat/', include(([
       path('Accueil/', students.AccueilListView.as_view(), name='first_page'),
       path('Profile/', students.profile_view, name='profile'),
       path('Profile_display/', students.profile, name='profile_dispaly'),
       
       

#Partie 2
#===================================<<<<#Projets >>>>===============================



        path('Projet/', students.HomeView.as_view(), name='lanceur_projet_home'),
        path('resultats_page/<int:pk>/', students.ExpertListView.as_view(), name='collaboration_page'),
        #Mesprojets
        path('Projets/', students.MesProjetsView.as_view(), name='mes_projets'),
        #mettre à jour
        path('projet/<int:pk>/', students.QuizUpdateView.as_view(), name='projet_change'),

       #detail projetMesTechnologies_list
        path('projet/detail/<slug:slug>', students.display_detail, name='projet_detail'),








#Partie 3 
#===================================<<<<#Colaborations>>>>===============================


        #collaboration
          path('collaborations/accueil', students.CollobarationListView.as_view(), name='collaborations'),
        #collaboration_potentielle
          path('collaborations/potentielles', students.PotentielleListView.as_view(), name='list_potentielle'),
         #collaboration_actuelle
          path('collaborations/actuelles', students.ActuelleListView.as_view(), name='list_actuelle'),
         #collaboration_contact
          path('collaborations/contact/<int:pk>/', students.sub_projet, name='potentielle_contact'), 
          
          path('chaine_de_Connaissance/<int:pk>/', students.ChaineListView.as_view(), name='chaine'),




#Partie 3 
#===================================<<<<#Technologies>>>>===============================
        #technologies
        path('technologies/Accueil', students.technologieListView.as_view(), name='technologies'),
        #La banque de technologies
        path('Technologies/Accueil/MesTechnologies', students.MesTechnologiesListView, name='MesTechnologies_list'),

        #Capteurs
        path('Capteurs/', students.CapteursView.as_view(), name='capteur_home'),
        path('capteur/ajouter/', students.CapteurCreateView.as_view(), name='capteur_add'),
        path('capteur/<int:pk>/modifier', students.CapteurUpdateView.as_view(), name='capteur_change'),
        path('capteur/<int:pk>/supprimer/', students.CapteurDeleteView.as_view(), name='capteur_delete'),
        path('capteur/detail/<slug:slug>', students.display_detail_capteur, name='capteur_detail'),


#Partie  4
     #Experts
        path('Experts/', students.ExpertsHomeListView.as_view(), name='expert_home'),
        path('Experts/<int:pk_1>/confirmation/<int:pk_2>/', students.sub_createxpert, name='expert_confirmation'),
        path('Collaboration_send/<int:pk_1>/<int:pk_2>/', students.sub_creatcollab, name='sub_creatcollab'),
        path('Experts/Annuaire', students.AnnuaireListView, name='Annuaire'),
        path('Experts/Liste', students.ExpertPotentielleListView.as_view(), name='liste'),
        path('Experts/Favoris/<int:pk_1>/confirmation/<int:pk_2>/', students.favoris, name='favoris'),


        path('free/', students.free, name='free'),




          
        path('equipe/projet/<int:pk>/', students.equipe_definition, name='equipe_projet'),
        path('equipe/projet/change/<int:pk>/', students.equipe_change.as_view(), name='equipe_change'),




      
   

        path('projet/add/', students.QuizCreateView.as_view(), name='projet_add'),
       
        path('projet/<int:pk>/delete/', students.QuizDeleteView.as_view(), name='projet_delete'),
        path('projet/detail/<slug:slug>', students.display_detail, name='projet_detail'),

        path('espace', students.ForumListView, name='forum_list'),
        path('espace/par/<username>/', students.ForumUserListView.as_view(), name='forum-by'),
        path('espace/par/profile/<username>/', students.ProfilUserListView.as_view(), name='forum_by_profile'),
        path('esm/projet/detail/<slug:slug>', students.forum_projet_detail, name='forum_detail'),

        
        #subject 


        #Gestion projet PDF 

        path('projet/pdf/<int:pk>', students.PdfGestionView.as_view(), name='gestionPDF'),

        #Recherche 

        path('expert', students.ExpertsListView, name='experts_list'),
        path('capteur', students.CapteurListView, name='capteurs_list'),
        path('partager/<int:pk>/', students.Publi_projet, name='publi_projet'),
        path('interests/', students.StudentInterestsView.as_view(), name='student_interests'),
        path('', students.QuizListView.as_view(), name='quiz_list'),
        path('mes_projet/', students.QuizMesView.as_view(), name='projet_list'),
        path('taken/', students.TakenQuizListView.as_view(), name='taken_quiz_list'),
        path('quiz/<int:pk>/', students.take_quiz, name='take_quiz'),
        path('_idées/', students.BoiteListView, name='boite_list'),
        path('_idées/form', students.IdeeCreateView.as_view(), name='idee_form'),
        ], 'classroom'), namespace='students')),



#Partie 3 
#===================================<<<<#Boites à idées>>>>===============================
        


]

django_school/django_school/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf.urls.static import static
from classroom.views import classroom, students, teachers
import notifications.urls
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext








    
 
urlpatterns = [
    
 
   
]
   

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




urlpatterns += i18n_patterns (
    path('', classroom.home, name='home'),
    path('Cap-Mat', include('classroom.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', classroom.SignUpView.as_view(), name='signup'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('reset-password', PasswordResetView.as_view(), name='password_reset'),
    path('reset-password/done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-password/confirm/<uidb64>[0-9A-Za-z]+)-<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset-password/complete/', PasswordResetCompleteView.as_view(),name='password_reset_complete'),

    
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_school/notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    #Notification list
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    path('Inbox/', views.CommentNoticeListView_read.as_view(), name='inbox'),

    #Update notification status
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
    path('update/<int:notice_id>', views.CommentNoticeUpdateView.as_view(), name='update_article'),
       #Update notification status
    path('list/notification', views.ExpertNoticeUpdateView.as_view(), name='notification_expert'),
   
]

django_school/classroom/views/classroom.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def home(request):
    if request.user.is_authenticated:
        if request.user.is_student:
            return redirect('students:first_page')
        else:
            return redirect('students:first_page')
            
    return render(request, 'Home_Page/index.html')

django_school/classroom/templates/capteurs/home_page.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Transitive by TEMPLATED
	templated.co @templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
	<head>
		<title>CapMat</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{% static 'template/assets/css/main.css' %}" />
		<link rel="stylesheet" href="{% static 'template/assets/css/main.css' %}" />
		<link rel="stylesheet" href="{%  static  'css/style.css' %}">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
	  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
	  <link rel="stylesheet" href="{%  static 'collaboration/assets/css/main.css' %}"  />

	</head>
	<body class="subpage">

		<!-- Header -->
			<header id="header">
				<div class="logo"><a href="index.html">CapMat <span>Application</span></a></div>
				<a href="#menu" class="toggle"><span>Menu</span></a>
			</header>

		<!-- Nav -->
			<nav id="menu">
				<ul class="links">
					<li><a href="{% url 'students:first_page' %}">Accueil </a></li>
					<li><a href="{% url 'students:lanceur_projet_home' %}">Nouveau Projet</a></li>
					<li><a href="{% url 'students:mes_projets' %}">Mes Projets</a></li>
					<li><a href="{% url 'students:collaborations' %}">Mes Collaborations</a></li>
					<li><a href="{% url 'students:capteur_home' %}">Mes Capteurs</a></li>
					<li><a href="{% url 'students:profile'%}">Profile</a></li>
					<li><a href="{% url 'logout' %}">Se déconnecter</a></li>
				</ul>
			</nav>

		<!-- One -->


		



			<section id="theree" class="wrapper style3">
				<div class="inner">

					<header class="align-center">
						<h2>Consultation de mes projets</h2>
						<p>Dans la section « Mes projets », vous accédez à l’ensemble de vos projets ainsi qu’à la liste d’experts es experts correspondant aux caractéristiques de chaqu'un de vos projets.</p>
					</header>

				
			
				</div>
			</section>

			<section id="theree" class="wrapper style1">
				<div class="inner">

				
					<div class="flex flex-3">

            <div class="col-md-8 blog-content">

              {% for quiz in quizzes %}
              
        
              <div class="sidebar-box" style="  box-shadow: 2px 2px 15px grey;
              border-radius: 6px;" >
    
          <a href="{% url 'students:capteur_change' quiz.pk %}" class="button alt">
            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
            <span><strong>Modifier</strong></span>            
        </a>
        
     
    
       
               <h4>{{ quiz.nom_capteur }}</h4>
                        <p >{{ quiz.description_projet}}</p>
                        <small><a href="tech-single.html" title="">{{quiz.created_at}}</a></small>
                
                </div>
    
                {% empty %}
                <div class="blog-list clearfix">
                  <div class="blog-box row">
                    <div class="blog-meta big-meta col-md-10">
                       
                   
                
    
                      <p style="text-align: justify;">Vous n'avez pas encore ajouter aucun capteur dans votre sélection</p>
                        <a href="{% url 'students:capteur_add' %}" title="">Commencer</a></p>
          
                      
                      </div><!-- end col -->
    
                    
                  </div><!-- end blog-box -->
                </div>   
                                                            
               
         {% endfor %} 
    
              </div>

              <div class="col-md-4 sidebar">
        
                <div class="sidebar-box">
                  <div class="categories">
                    <h3>Categories </h3>
                  
                    <li><a href="{% url 'students:capteur_add' %}">Ajouter un nouveau capteur <span><i class="material-icons">computer</i></span></a></li>
                    <li><a href="{% url 'students:capteur_home' %}">Mes Capteurs <span><i class="material-icons">cloud</i></span></a></li>
                    <li><a href="{% url 'students:profile' %}">Profile <span><i class="material-icons">person</i></span></a></li>
                    
                 
                
                  </div>
                </div>
            
        
             
              </div>
				
					</div>
				</div>
			</section>




			<footer id="footer">
				<div class="copyright">
					<ul class="icons">
						<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
						<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
						<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
						<li><a href="#" class="icon fa-snapchat"><span class="label">Snapchat</span></a></li>
					</ul>
					<p>	&copy; copyright: 2020 <a href="https://templated.co/">ERPI (Research team on innovation process)</a>.</p>
				</div>
			</footer>













		</div> 
		<!-- Scripts -->
		<script src="{%  static 'collaboration/assets/js/jquery.min.js' %}"></script>
		<script src="{%  static 'collaboration/assets/js/jquery.scrolly.min.js' %}"></script>
		<script src="{%  static 'collaboration/assets/js/jquery.scrollex.min.js' %}"></script>
		<script src="{%  static 'collaboration/assets/js/skel.min.js' %}"></script>
		<script src="{%  static 'collaboration/assets/js/util.js' %}"></script>
		<script src="{%  static 'collaboration/assets/js/main.js' %}"></script>

	</body>
</html>