django_school/classroom/urls.py
from django.urls import include, path

from .views import classroom, students

urlpatterns = [

    
       path('home_page/', students.home_page.as_view(), name='home_page'),
       path('mots_cles/add/', students.SubjectCreateView.as_view(), name='subject_add'),
       path('domaine/add/', students.DomaineCreateView.as_view(), name='domaine_add'),
       path('type/add/', students.TypeCapteurCreateView.as_view(), name='type_add'),
       path('flyer/', students.FlyerView.as_view(), name='flyer'),
       path('profile_detail/<int:pk_1>/<int:pk_2>/', students.StudentListView.as_view(), name='student_profile'),
       path('collaboration/potentielle/<int:pk_1>/profil_projet/<int:pk_2>/', students.Potentielle_profil.as_view(), name='student_profile_projet'),
       path('expert/<int:pk_1>/', students.expert_annuaire.as_view(), name='annuaire_expert'),
       path('pdf/', students.GeneratePdf.as_view()),
       path('subscribe/', students.subscribe, name = 'subscribe'),
       path('confirmation/<int:pk_1>/<int:pk_2>/<int:pk_3>/<int:notice_id>', students.confirmation_projet, name = 'confirmation_projet'),
       path('confirmation/expert/<int:pk_1>/<int:pk_2>/<int:pk_3>/<int:notice_id>', students.confirmation_expert, name = 'confirmation_expert'),
       path('projet/public/detail/<slug:slug>', students.display_detail_public, name='projet_public'),
       path('projet/public/collaboration/<slug:slug>', students.display_detail_public_coll, name='display_detail_public_coll'),
       path('projet/public/collaboration/actu/<slug:slug>', students.display_detail_public_coll_ac, name='display_detail_public_coll_ac'),
       path('capteur/public/detail/<slug:slug>', students.display_detail_capteur_public, name='capteur_public'),
       path('espace/projet/public/detail/<slug:slug>', students.espace_public, name='espace_public'),
       path('espace/capteur/public/detail/<slug:slug>', students.espace_capteur_public, name='espace_capteur_public'),
       path('boite_a_idees', students.index, name='question_an'),
       path('question/<int:qid>/<slug:qslug>', students.viewquestion),
       path('ask-question', students.askquestion, name='ask_question'),
       path('ajax-answer-question', students.ajaxanswerquestion),
       path('CapMat/', include(([
       path('Accueil/', students.AccueilListView.as_view(), name='first_page'),
       path('Profile/', students.profile_view, name='profile'),
       path('Profile_display/', students.profile, name='profile_dispaly'),
       
       

#Partie 2
#===================================<<<<#Projets >>>>===============================



        path('Projet/', students.HomeView.as_view(), name='lanceur_projet_home'),
        path('resultats_page/<int:pk>/', students.ExpertListView.as_view(), name='collaboration_page'),
        #Mesprojets
        path('Projets/', students.MesProjetsView.as_view(), name='mes_projets'),
        #mettre à jour
        path('projet/<int:pk>/', students.QuizUpdateView.as_view(), name='projet_change'),

       #detail projetMesTechnologies_list
        path('projet/detail/<slug:slug>', students.display_detail, name='projet_detail'),








#Partie 3 
#===================================<<<<#Colaborations>>>>===============================


        #collaboration
          path('collaborations/accueil', students.CollobarationListView.as_view(), name='collaborations'),
        #collaboration_potentielle
          path('collaborations/potentielles', students.PotentielleListView.as_view(), name='list_potentielle'),
         #collaboration_actuelle
          path('collaborations/actuelles', students.ActuelleListView.as_view(), name='list_actuelle'),
         #collaboration_contact
          path('collaborations/contact/<int:pk>/', students.sub_projet, name='potentielle_contact'), 
          
          path('chaine_de_Connaissance/<int:pk>/', students.ChaineListView.as_view(), name='chaine'),




#Partie 3 
#===================================<<<<#Technologies>>>>===============================
        #technologies
        path('technologies/Accueil', students.technologieListView.as_view(), name='technologies'),
        #La banque de technologies
        path('Technologies/Accueil/MesTechnologies', students.MesTechnologiesListView, name='MesTechnologies_list'),

        #Capteurs
        path('Capteurs/', students.CapteursView.as_view(), name='capteur_home'),
        path('capteur/ajouter/', students.CapteurCreateView.as_view(), name='capteur_add'),
        path('capteur/<int:pk>/modifier', students.CapteurUpdateView.as_view(), name='capteur_change'),
        path('capteur/<int:pk>/supprimer/', students.CapteurDeleteView.as_view(), name='capteur_delete'),
        path('capteur/detail/<slug:slug>', students.display_detail_capteur, name='capteur_detail'),


#Partie  4
     #Experts
        path('Experts/', students.ExpertsHomeListView.as_view(), name='expert_home'),
        path('Experts/<int:pk_1>/confirmation/<int:pk_2>/', students.sub_createxpert, name='expert_confirmation'),
        path('Collaboration_send/<int:pk_1>/<int:pk_2>/', students.sub_creatcollab, name='sub_creatcollab'),
        path('Experts/Annuaire', students.AnnuaireListView, name='Annuaire'),
        path('Experts/Liste', students.ExpertPotentielleListView.as_view(), name='liste'),
        path('Experts/Favoris/<int:pk_1>/confirmation/<int:pk_2>/', students.favoris, name='favoris'),


        path('free/', students.free, name='free'),




          
        path('equipe/projet/<int:pk>/', students.equipe_definition, name='equipe_projet'),
        path('equipe/projet/change/<int:pk>/', students.equipe_change.as_view(), name='equipe_change'),




      
   

        path('projet/add/', students.QuizCreateView.as_view(), name='projet_add'),
       
        path('projet/<int:pk>/delete/', students.QuizDeleteView.as_view(), name='projet_delete'),
        path('projet/detail/<slug:slug>', students.display_detail, name='projet_detail'),

        path('espace', students.ForumListView, name='forum_list'),
        path('espace/par/<username>/', students.ForumUserListView.as_view(), name='forum-by'),
        path('espace/par/profile/<username>/', students.ProfilUserListView.as_view(), name='forum_by_profile'),
        path('esm/projet/detail/<slug:slug>', students.forum_projet_detail, name='forum_detail'),

        
        #subject 


        #Gestion projet PDF 

        path('projet/pdf/<int:pk>', students.PdfGestionView.as_view(), name='gestionPDF'),

        #Recherche 

        path('expert', students.ExpertsListView, name='experts_list'),
        path('capteur', students.CapteurListView, name='capteurs_list'),
        path('partager/<int:pk>/', students.Publi_projet, name='publi_projet'),
        path('interests/', students.StudentInterestsView.as_view(), name='student_interests'),
        path('', students.QuizListView.as_view(), name='quiz_list'),
        path('mes_projet/', students.QuizMesView.as_view(), name='projet_list'),
        path('taken/', students.TakenQuizListView.as_view(), name='taken_quiz_list'),
        path('quiz/<int:pk>/', students.take_quiz, name='take_quiz'),
        path('_idées/', students.BoiteListView, name='boite_list'),
        path('_idées/form', students.IdeeCreateView.as_view(), name='idee_form'),
        ], 'classroom'), namespace='students')),



#Partie 3 
#===================================<<<<#Boites à idées>>>>===============================
        


]

django_school/django_school/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf.urls.static import static
from classroom.views import classroom, students, teachers
import notifications.urls
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext








    
 
urlpatterns = [
    
 
   
]
   

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




urlpatterns += i18n_patterns (
    path('', classroom.home, name='home'),
    path('Cap-Mat', include('classroom.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', classroom.SignUpView.as_view(), name='signup'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('reset-password', PasswordResetView.as_view(), name='password_reset'),
    path('reset-password/done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-password/confirm/<uidb64>[0-9A-Za-z]+)-<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset-password/complete/', PasswordResetCompleteView.as_view(),name='password_reset_complete'),

    
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_school/notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    #Notification list
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    path('Inbox/', views.CommentNoticeListView_read.as_view(), name='inbox'),

    #Update notification status
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
    path('update/<int:notice_id>', views.CommentNoticeUpdateView.as_view(), name='update_article'),
       #Update notification status
    path('list/notification', views.ExpertNoticeUpdateView.as_view(), name='notification_expert'),
   
]

django_school/classroom/views/classroom.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def home(request):
    if request.user.is_authenticated:
        if request.user.is_student:
            return redirect('students:first_page')
        else:
            return redirect('students:first_page')
            
    return render(request, 'Home_Page/index.html')

django_school/classroom/templates/classroom/students/_header.html
<h2>Quizzes</h2>
<p class="text-muted">
  Subjects:{% for subject in user.student.interests.all %} {{ subject.get_html_badge }}{% endfor %}
  <a href="{% url 'students:student_interests' %}"><small>(update interests)</small></a>
</p>

<ul class="nav nav-tabs mb-3">
  <li class="nav-item">
    <a class="nav-link{% if active == 'new' %} active{% endif %}" href="{% url 'students:quiz_list' %}">New</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if active == 'taken' %} active{% endif %}" href="{% url 'students:taken_quiz_list' %}">Taken</a>
  </li>
</ul>

django_school/classroom/templates/classroom/students/display_projet.html
{% load crispy_forms_tags %}
{% load humanize %}
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <title>CapMat </title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
  <link rel="stylesheet" href="fonts/icomoon/style.css' %}">

  <link rel="stylesheet" href="{%  static  'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{%  static  'css/jquery-ui.css' %}">
  <link rel="stylesheet" href="{%  static  'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{%  static  'css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{%  static  'css/owl.theme.default.min.css' %}">

  <link rel="stylesheet" href="{%  static  'css/jquery.fancybox.min.css' %}">

  <link rel="stylesheet" href="{%  static  'css/bootstrap-datepicker.css' %}">

  <link rel="stylesheet" href="fonts/flaticon/font/flaticon.css' %}">

  <link rel="stylesheet" href="{%  static  'css/aos.css' %}">

  <link rel="stylesheet" href="{%  static  'css/style.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>




<style>


a.btn:hover {
  -webkit-transform: scale(1.1);
  -moz-transform: scale(1.1);
  -o-transform: scale(1.1);
}
a.btn {
  -webkit-transform: scale(0.8);
  -moz-transform: scale(0.8);
  -o-transform: scale(0.8);
  -webkit-transition-duration: 0.5s;
  -moz-transition-duration: 0.5s;
  -o-transition-duration: 0.5s;
}


p {
     width: 500px;
     white-space: nowrap;
     overflow: hidden;
     text-overflow: ellipsis;
}



.box {

  background-color: lightgray;
  padding: 40px;
  margin: 40px;
  width: 600px;
  height: 200px;
}

.alternate {
  box-sizing: border-box;
}
    


</style>
</head>

<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">



  <div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>


    <header class="site-navbar" role="banner" style="background-image: url({% static 'images/img_2.jpg' %});" data-aos="fade">
      

 



      <div class="container">
        <div class="row align-items-center">
          
          <div class="col-6 col-xl-2">
            <h1 class="mb-0 site-logo"><a href="index.html" class="h2 mb-0" style="color: #007bff">CapMat<span class="text-primary">.</span> </a></h1>
          </div>
          <div class="col-12 col-md-10 d-none d-xl-block">
            <nav class="site-navigation position-relative text-right" role="navigation">

   
                    <li><a href="" class="nav-link">Logged in as <strong>{{ user.username }}</strong></a></li>
                  
                  </ul>
                </li>

              </ul>
            </nav>
          </div>



          <div class="col-6 d-inline-block d-xl-none ml-md-0 py-3" style="position: relative; top: 3px;"><a href="#" class="site-menu-toggle js-menu-toggle float-right"><span class="icon-menu h3"></span></a></div>

        </div>
      </div>






    </header>



  
    
    
    
    <section class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-md-8 blog-content">
         

         <a href="{% url 'students:projet_add' %}" class="btn btn-primary a-btn-slide-text">
              <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
              <span><strong></strong></span>            
          </a>
          <a href="{% url 'students:projet_change' post.pk %}" class="btn btn-primary a-btn-slide-text">
            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
            <span><strong></strong></span>            
        </a>
        <a href="{% url 'students:projet_delete' post.pk  %}" class="btn btn-primary a-btn-slide-text">
          <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
           <span><strong></strong></span>            
       </a>

       <a href="{% url 'students:lanceur_projet_home'  %}" class="btn btn-primary a-btn-slide-text">
        <span  aria-hidden="true"></span>
         <span><strong>Annuler</strong></span>            
     </a>
            {% if request.user == post.user %} 
  
            <a href="{% url 'edit_projet' post.pk %}" class="btn btn-primary a-btn-slide-text">
              <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
              <span><strong>Edit</strong></span>            
          </a>
      
          <a href="#" class="btn btn-primary a-btn-slide-text">
             <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
              <span><strong>Delete</strong></span>            
          </a>
         
            {% else %}
    
            {% endif  %}

            <h1> {{ post.titre_projet }}</h1>
            <p class=" text-muted">{{ post.user.username }} | {{post.created_at | naturaltime}}</p>
            <div class="col-md-8 card mb-4  mt-3 left  top">
              <div class="card-body">
              




                 <label for="textarea-input" class=" form-control-label">Déscription du projet</label>
                  <p name="textarea-input" id="textarea-input" rows="9" placeholder="Content..." class="form-control">{{ post.description_projet | safe }}</textarea></p>
              
              
                    <label for="textarea-input" class=" form-control-label">Type du capteur </label>
                    <p name="textarea-input" id="textarea-input" rows="9" placeholder="Content..." class="form-control">{{ post.type_capteur | safe }}</textarea></p>
                
                      <label for="textarea-input" class=" form-control-label">Type d’événement à détecter </label>
                      <p name="textarea-input" id="textarea-input" rows="9" placeholder="Content..." class="form-control">{{ post.type_evt | safe }}</textarea></p>
                  
                        <label for="textarea-input" class=" form-control-label">Nature d’événement à détecter</label>
                        <p name="textarea-input" id="textarea-input" rows="9" placeholder="Content..." class="form-control">{{ post.nature_evt | safe }}</textarea></p>
                    
                          <label for="textarea-input" class=" form-control-label">Grandeur de l’événement à détecter</label>
                          <p name="textarea-input" id="textarea-input" rows="9" placeholder="Content..." class="form-control">{{ post.grandeur_evt | safe }}</textarea></p>
                          <label for="textarea-input" class=" form-control-label">L'environnement de l'événement à détecter</label>
                          <p name="textarea-input" id="textarea-input" rows="9" placeholder="Content..." class="form-control">{{ post.envirennoment_evt | safe }}</textarea></p>
                          <label for="textarea-input" class=" form-control-label">Etendue de mesure</label>
                          <p name="textarea-input" id="textarea-input" rows="9" placeholder="Content..." class="form-control">{{ post.etendue | safe }}</textarea></p>
                          <label for="textarea-input" class=" form-control-label">Sensibilité</label>
                          <p name="textarea-input" id="textarea-input" rows="9" placeholder="Content..." class="form-control">{{ post.sensibilite | safe }}</textarea></p>
                                  
                          <label for="textarea-input" class=" form-control-label">Résolution</label>
                          <p name="textarea-input" id="textarea-input" rows="9" placeholder="Content..." class="form-control">{{ post.resolution | safe }}</textarea></p>
                            
                          <label for="textarea-input" class=" form-control-label">Précision </label>
                          <p name="textarea-input" id="textarea-input" rows="9" placeholder="Content..." class="form-control">{{ post.precision | safe }}</textarea></p>
                                  


                          <label for="textarea-input" class=" form-control-label">Rapidité </label>
                          <p name="textarea-input" id="textarea-input" rows="9" placeholder="Content..." class="form-control">{{ post.rapidite | safe }}</textarea></p>
                                  


                          <label for="textarea-input" class=" form-control-label">Dimensions </label>
                          <p name="textarea-input" id="textarea-input" rows="9" placeholder="Content..." class="form-control">{{ post.dimensions | safe }}</textarea></p>
                                  









              
         
              
               
        
        
        
        
        
        
        
        
        
              </div>
            </div>
            
        
            <div class="col-md-8 card mb-4  mt-3 ">
              <div class="card-body">
                <!-- comments -->
                <p> Nombre des commentaires pour ce projet est de <strong>{{ comments.count }}</strong>  </p>
        
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                  <p class="font-weight-bold">
                    {{ comment.name }}
                    <span class=" text-muted font-weight-normal">
                      {{ comment.created_on }}
                    </span>
                  </p>
                  {{ comment.body | linebreaks }}
                </div>
                {% endfor %}
              </div>
            </div>
       














      
      
      
      
      
      
   
























     
    
    
  
          </div>
          <div class="col-md-4 sidebar">
        

            <div class="sidebar-box">
              <div class="categories">
                <h3>Categories</h3>
                <li><a href="{% url 'home' %}"><span><i class="material-icons">home</i></span> Accueil </a></li>
                <li><a href="{% url 'students:projet_add' %}"> <span><i class="material-icons">computer</i></span>Nouveau projet</a></li>
                <li><a href="{% url 'students:lanceur_projet_home' %}">Mes Projets <span><i class="material-icons">attachment</i></span></a></li>
                <li><a href="{% url 'students:collaborations' %}">Mes Proposition de collaborations <span><i class="material-icons">cloud</i></span></a></li>
                <li><a href="{% url 'students:capteur_add' %}">Mes Capteurs <span><i class="material-icons">traffic</i></span></a></li>
                <li><a href="{% url 'students:profile' %}">Profile <span><i class="material-icons">person</i></span></a></li>
                <li><a href="{% url 'logout' %}">Se déconnecter <span><i class="fa fa-sign-out"></i></span></a></li>
             
            
              </div>
            </div>
        
    
         
          </div>
        </div>
      </div>
    </section>

    <footer class="site-footer">
      <div class="container">
        <div class="row">
          
          <a href="https://erpi.univ-lorraine.fr/">                  Copyright &copy;
            <script>document.write(new Date().getFullYear());</script> All rights reserved | Equipe de Recherche sur les Processus Innovatifs, ERPI </a>
            
           
   
          </div>
        </div>
      
      </div>
    </footer>

  </div> <!-- .site-wrap -->

  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>
  <script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
  <script src="{% static 'js/jquery.sticky.js' %}"></script>
  <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>


  <script src="{% static 'js/main.js' %}"></script>


</body>

</html>





                                  
                                                                                   
                                            
                                            
                        

django_school/classroom/templates/classroom/students/interests_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h2 class="mb-3">Update your interests</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'students:quiz_list' %}" class="btn btn-outline-secondary">Nevermind</a>
  </form>
{% endblock %}

django_school/classroom/templates/classroom/students/projet_list.html
{% extends 'base.html' %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">My Quizzes</li>
    </ol>
  </nav>
  <h2 class="mb-3">My Quizzes</h2>
  <a href="{% url 'teachers:quiz_add' %}" class="btn btn-primary mb-3" role="button">Add quiz</a>
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Quiz</th>
          <th>Subject</th>
          <th>Questions</th>
          <th>Taken</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for quiz in quizzes %}
          <tr>
            <td class="align-middle"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></td>
            <td class="align-middle">{{ quiz.subject.get_html_badge }}</td>
            <td class="align-middle">{{ quiz.questions_count }}</td>
            <td class="align-middle">{{ quiz.taken_count }}</td>
            <td class="text-right">
              <a href="{% url 'teachers:quiz_results' quiz.pk %}" class="btn btn-primary">View results</a>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="5">You haven't created any quiz yet.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

django_school/classroom/templates/classroom/students/quiz_delete_confirm.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

  <h2 class="mb-3">Confirmer la suppression</h2>
  <p class="lead">Voulez-vous vraiment supprimer le projet <strong>"{{ quiz.titre_projet }}"</strong>? Il n'y a pas de retour en arrière.</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-lg">Supprimer</button>
    <a href="{% url 'students:lanceur_projet_home' %}" class="btn btn-outline-secondary btn-lg" role="button">Annuler</a>
  </form>
{% endblock %}

django_school/classroom/templates/classroom/students/quiz_list.html
{% extends 'base.html' %}

{% block content %}
  {% include 'classroom/students/_header.html' with active='new' %}
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Quiz</th>
          <th>Subject</th>
          <th>Length</th>sub
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for quiz in quizzes %}
          <tr>
            <td class="align-middle">{{ quiz.name }}</td>
            <td class="align-middle">{{ quiz.subject.get_html_badge }}</td>
            <td class="align-middle">{{ quiz.questions_count }} questions</td>
            <td class="text-right">
              <a href="{% url 'students:take_quiz' quiz.pk %}" class="btn btn-primary">Start quiz</a>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="4">No quiz matching your interests right now.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>


    <a href="{% url 'students:projet_add' %}">add pojet</a>
    <a href="{% url 'students:projet_list' %}">MESPROJETS</a>
    <a href="{% url 'students:profile' %}">Profile</a>

    
  </div>
{% endblock %}

django_school/classroom/templates/classroom/students/take_quiz_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="progress mb-3">
    <div class="progress-bar" role="progressbar" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ progress }}%"></div>
  </div>
  <h2 class="mb-3">{{ quiz.name }}</h2>
  <p class="lead">{{ question.text }}</p>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Next →</button>
  </form>
{% endblock %}

django_school/classroom/templates/classroom/students/taken_quiz_list.html
{% extends 'base.html' %}

{% block content %}
  {% include 'classroom/students/_header.html' with active='taken' %}
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Quiz</th>
          <th>Subject</th>
          <th>Score</th>
        </tr>
      </thead>
      <tbody>
        {% for taken_quiz in taken_quizzes %}
          <tr>
            <td>{{ taken_quiz.quiz.name }}</td>
            <td>{{ taken_quiz.quiz.subject.get_html_badge }}</td>
            <td>{{ taken_quiz.score }}</td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="3">You haven't completed any quiz yet.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}