django_school/classroom/urls.py
from django.urls import include, path

from .views import classroom, students

urlpatterns = [

    
       path('home_page/', students.home_page.as_view(), name='home_page'),
       path('mots_cles/add/', students.SubjectCreateView.as_view(), name='subject_add'),
       path('domaine/add/', students.DomaineCreateView.as_view(), name='domaine_add'),
       path('type/add/', students.TypeCapteurCreateView.as_view(), name='type_add'),
       path('flyer/', students.FlyerView.as_view(), name='flyer'),
       path('profile_detail/<int:pk_1>/<int:pk_2>/', students.StudentListView.as_view(), name='student_profile'),
       path('collaboration/potentielle/<int:pk_1>/profil_projet/<int:pk_2>/', students.Potentielle_profil.as_view(), name='student_profile_projet'),
       path('expert/<int:pk_1>/', students.expert_annuaire.as_view(), name='annuaire_expert'),
       path('pdf/', students.GeneratePdf.as_view()),
       path('subscribe/', students.subscribe, name = 'subscribe'),
       path('confirmation/<int:pk_1>/<int:pk_2>/<int:pk_3>/<int:notice_id>', students.confirmation_projet, name = 'confirmation_projet'),
       path('confirmation/expert/<int:pk_1>/<int:pk_2>/<int:pk_3>/<int:notice_id>', students.confirmation_expert, name = 'confirmation_expert'),
       path('projet/public/detail/<slug:slug>', students.display_detail_public, name='projet_public'),
       path('projet/public/collaboration/<slug:slug>', students.display_detail_public_coll, name='display_detail_public_coll'),
       path('projet/public/collaboration/actu/<slug:slug>', students.display_detail_public_coll_ac, name='display_detail_public_coll_ac'),
       path('capteur/public/detail/<slug:slug>', students.display_detail_capteur_public, name='capteur_public'),
       path('espace/projet/public/detail/<slug:slug>', students.espace_public, name='espace_public'),
       path('espace/capteur/public/detail/<slug:slug>', students.espace_capteur_public, name='espace_capteur_public'),
       path('boite_a_idees', students.index, name='question_an'),
       path('question/<int:qid>/<slug:qslug>', students.viewquestion),
       path('ask-question', students.askquestion, name='ask_question'),
       path('ajax-answer-question', students.ajaxanswerquestion),
       path('CapMat/', include(([
       path('Accueil/', students.AccueilListView.as_view(), name='first_page'),
       path('Profile/', students.profile_view, name='profile'),
       path('Profile_display/', students.profile, name='profile_dispaly'),
       
       

#Partie 2
#===================================<<<<#Projets >>>>===============================



        path('Projet/', students.HomeView.as_view(), name='lanceur_projet_home'),
        path('resultats_page/<int:pk>/', students.ExpertListView.as_view(), name='collaboration_page'),
        #Mesprojets
        path('Projets/', students.MesProjetsView.as_view(), name='mes_projets'),
        #mettre à jour
        path('projet/<int:pk>/', students.QuizUpdateView.as_view(), name='projet_change'),

       #detail projetMesTechnologies_list
        path('projet/detail/<slug:slug>', students.display_detail, name='projet_detail'),








#Partie 3 
#===================================<<<<#Colaborations>>>>===============================


        #collaboration
          path('collaborations/accueil', students.CollobarationListView.as_view(), name='collaborations'),
        #collaboration_potentielle
          path('collaborations/potentielles', students.PotentielleListView.as_view(), name='list_potentielle'),
         #collaboration_actuelle
          path('collaborations/actuelles', students.ActuelleListView.as_view(), name='list_actuelle'),
         #collaboration_contact
          path('collaborations/contact/<int:pk>/', students.sub_projet, name='potentielle_contact'), 
          
          path('chaine_de_Connaissance/<int:pk>/', students.ChaineListView.as_view(), name='chaine'),




#Partie 3 
#===================================<<<<#Technologies>>>>===============================
        #technologies
        path('technologies/Accueil', students.technologieListView.as_view(), name='technologies'),
        #La banque de technologies
        path('Technologies/Accueil/MesTechnologies', students.MesTechnologiesListView, name='MesTechnologies_list'),

        #Capteurs
        path('Capteurs/', students.CapteursView.as_view(), name='capteur_home'),
        path('capteur/ajouter/', students.CapteurCreateView.as_view(), name='capteur_add'),
        path('capteur/<int:pk>/modifier', students.CapteurUpdateView.as_view(), name='capteur_change'),
        path('capteur/<int:pk>/supprimer/', students.CapteurDeleteView.as_view(), name='capteur_delete'),
        path('capteur/detail/<slug:slug>', students.display_detail_capteur, name='capteur_detail'),


#Partie  4
     #Experts
        path('Experts/', students.ExpertsHomeListView.as_view(), name='expert_home'),
        path('Experts/<int:pk_1>/confirmation/<int:pk_2>/', students.sub_createxpert, name='expert_confirmation'),
        path('Collaboration_send/<int:pk_1>/<int:pk_2>/', students.sub_creatcollab, name='sub_creatcollab'),
        path('Experts/Annuaire', students.AnnuaireListView, name='Annuaire'),
        path('Experts/Liste', students.ExpertPotentielleListView.as_view(), name='liste'),
        path('Experts/Favoris/<int:pk_1>/confirmation/<int:pk_2>/', students.favoris, name='favoris'),


        path('free/', students.free, name='free'),




          
        path('equipe/projet/<int:pk>/', students.equipe_definition, name='equipe_projet'),
        path('equipe/projet/change/<int:pk>/', students.equipe_change.as_view(), name='equipe_change'),




      
   

        path('projet/add/', students.QuizCreateView.as_view(), name='projet_add'),
       
        path('projet/<int:pk>/delete/', students.QuizDeleteView.as_view(), name='projet_delete'),
        path('projet/detail/<slug:slug>', students.display_detail, name='projet_detail'),

        path('espace', students.ForumListView, name='forum_list'),
        path('espace/par/<username>/', students.ForumUserListView.as_view(), name='forum-by'),
        path('espace/par/profile/<username>/', students.ProfilUserListView.as_view(), name='forum_by_profile'),
        path('esm/projet/detail/<slug:slug>', students.forum_projet_detail, name='forum_detail'),

        
        #subject 


        #Gestion projet PDF 

        path('projet/pdf/<int:pk>', students.PdfGestionView.as_view(), name='gestionPDF'),

        #Recherche 

        path('expert', students.ExpertsListView, name='experts_list'),
        path('capteur', students.CapteurListView, name='capteurs_list'),
        path('partager/<int:pk>/', students.Publi_projet, name='publi_projet'),
        path('interests/', students.StudentInterestsView.as_view(), name='student_interests'),
        path('', students.QuizListView.as_view(), name='quiz_list'),
        path('mes_projet/', students.QuizMesView.as_view(), name='projet_list'),
        path('taken/', students.TakenQuizListView.as_view(), name='taken_quiz_list'),
        path('quiz/<int:pk>/', students.take_quiz, name='take_quiz'),
        path('_idées/', students.BoiteListView, name='boite_list'),
        path('_idées/form', students.IdeeCreateView.as_view(), name='idee_form'),
        ], 'classroom'), namespace='students')),



#Partie 3 
#===================================<<<<#Boites à idées>>>>===============================
        


]

django_school/django_school/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf.urls.static import static
from classroom.views import classroom, students, teachers
import notifications.urls
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext








    
 
urlpatterns = [
    
 
   
]
   

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




urlpatterns += i18n_patterns (
    path('', classroom.home, name='home'),
    path('Cap-Mat', include('classroom.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', classroom.SignUpView.as_view(), name='signup'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('reset-password', PasswordResetView.as_view(), name='password_reset'),
    path('reset-password/done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-password/confirm/<uidb64>[0-9A-Za-z]+)-<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset-password/complete/', PasswordResetCompleteView.as_view(),name='password_reset_complete'),

    
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_school/notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    #Notification list
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    path('Inbox/', views.CommentNoticeListView_read.as_view(), name='inbox'),

    #Update notification status
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
    path('update/<int:notice_id>', views.CommentNoticeUpdateView.as_view(), name='update_article'),
       #Update notification status
    path('list/notification', views.ExpertNoticeUpdateView.as_view(), name='notification_expert'),
   
]

django_school/notice/models.py
from django.db import models

# Create your models here.

django_school/notice/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from classroom.models import Quiz, Student
from django.shortcuts import get_object_or_404


class CommentNoticeListView(LoginRequiredMixin, ListView):
    "" "notification list" ""
    #Name of the context
    context_object_name = 'notices'
    #Template location
    template_name = 'notice/list.html'
    #Login redirection
    login_url = '/userprofile/login/'

    #Query set for unread notifications
    def get_queryset(self):
        return self.request.user.notifications.unread()

class CommentNoticeListView_read(LoginRequiredMixin, ListView):
    "" "notification list" ""
    #Name of the context
    context_object_name = 'notices'
    #Template location
    template_name = 'notice/inbox.html'
 
    #Query set for unread notifications
    def get_queryset(self):
        return self.request.user.notifications.unread()

   
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(CommentNoticeListView_read, self).get_context_data(**kwargs)
        # Add in the publisher
        context['reads'] = self.request.user.notifications.read()
        return context

    

class CommentNoticeUpdateView(View):
    "" "update notification status" ""
    #Processing get requests
    def get(self, request):
        #Get unread message
        notice_id = request.GET.get('notice_id')
        #Update single notice
        if notice_id:
            request.user.notifications.get(id=notice_id).mark_as_read()
            return redirect('notice:inbox')
        #Update all notifications
        else:
            request.user.notifications.mark_all_as_read()
            return redirect('notice:inbox')



class ExpertNoticeUpdateView(View):
    "" "update notification status" ""
    #Processing get requests
    def get(self, request):
        #Get unread message
        notice_id = request.GET.get('notice_id')
        #Update single notice
        if notice_id:
            article = get_object_or_404(Student,pk=request.GET.get('article_id'))
            request.user.notifications.get(id=notice_id).mark_as_read()
            return redirect('students:projet_detail', article.slug  )
        #Update all notifications
        else:
            return redirect('notice:list')

django_school/notice/templates/expert_info.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}CapMat{% endblock title %}</title>
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <meta name="description" content="An enterprise Social Network">
    <meta name="author" content="Sebastian Reyes">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->
    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Your stuff: Third-party CSS libraries go here -->
    <link rel="stylesheet" type="text/css" href="{% static 'boot/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!-- This file stores project-specific CSS -->
	<link href="{% static 'boot/css/bootcamp.css' %}?v=1" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'template/assets/css/main.css' %}" />
		 <!-- Google Fonts -->
		 <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700" rel="stylesheet">
		 <link href="https://fonts.googleapis.com/css?family=Raleway:100,200,300,400,500,600,700,800" rel="stylesheet">
		 <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900" rel="stylesheet">
 
		 <!-- Plugins -->
		 <link rel="stylesheet" href="{% static 'acro/css/plugins.css' %}" />
 
		 <!-- Core Style Css -->
		 <link rel="stylesheet" href="{% static 'acro/css/style.css'%}" />
		 
    {% endblock css %}
	{% block head %}{% endblock head %}
	
<style>


.notification {
  position: relative;
  width: 2em;
  height: 2em;
}
.notification svg {
  width: 2em;
  height: 2em;
}
.notification svg > path {
  fill: #FFFFFF;
}
.notification--bell {
  animation: bell 2.2s linear infinite;
  transform-origin: 50% 0%;
}
 .notification--bellClapper {
  animation: bellClapper 2.2s 0.1s linear infinite;
}
.notification--num {
  position: absolute;
  top: 0%;
  left: 60%;
  font-size: 1rem;
  border-radius: 50%;
  width: 1.75em;
  height: 1.75em;
  background-color: #FF4C13;
  
  color: #FFFFFF;
  text-align: center;
  line-height: 1.7em;
  animation: notification 3.2s ease;
}

@keyframes bell {
  0%, 25%, 75%, 100% {
    transform: rotate(0deg);
  }
  40% {
    transform: rotate(2deg);
  }
  45% {
    transform: rotate(-2deg);
  }
  55% {
    transform: rotate(1deg);
  }
  60% {
    transform: rotate(-1deg);
  }
}
@keyframes bellClapper {
  0%, 25%, 75%, 100% {
    transform: translateX(0);
  }
  40% {
    transform: translateX(-0.15em);
  }
  45% {
    transform: translateX(0.15em);
  }
  55% {
    transform: translateX(-0.1em);
  }
  60% {
    transform: translateX(0.1em);
  }
}
@keyframes notification {
  0%, 25%, 75%, 100% {
    opacity: 1;
  }
  30%, 70% {
    opacity: 0;
  }
}














</style>
  </head>
  <body>
    {% block body %}
  


	  
	{% load notifications_tags %}
		{% notifications_unread as unread_count %}
	


	  <nav class="navbar navbar-expand-lg " style="background-color:rgb(53, 49, 49)">
		<div class="container">

		<!-- Logo -->
		<a style="color: #FFFFFF;" href="{% url 'students:first_page' %}">
			CapMat       
		</a>

		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="icon-bar"><i class="fas fa-bars"></i></span>
		  </button>

		  <!-- navbar links -->
		  <div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'students:first_page' %}" data-scroll-nav="2">Accueil</a>
				  </li>
			
			  <li class="nav-item">
				<a class="nav-link" href="{% url 'students:lanceur_projet_home' %}">Nouveau Projet</a>
			  </li>
			  <li class="nav-item">
				<a class="nav-link" href="{% url 'students:mes_projets' %}" >Mes Projets</a>
		
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="{% url 'students:collaborations' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				 
					  Collaborations
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					  <a class="dropdown-item" href="">Mes Experts</a>
					  <div class="dropdown-divider"></div>
					  <a class="dropdown-item" href="">Annuaire des experts</a>
					</div>
				  </li>


				  <li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				 
					  Technologies
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					  <a class="dropdown-item" href="">Mes Experts</a>
					  <div class="dropdown-divider"></div>
					  <a class="dropdown-item" href="">Annuaire des experts</a>
					</div>
				  </li>

				  <li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				 
					  Experts
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					  <a class="dropdown-item" href="">Mes Experts</a>
					  <div class="dropdown-divider"></div>
					  <a class="dropdown-item" href="">Annuaire des experts</a>
					</div>
				  </li>

			  <li class="nav-item"><a class="nav-link" href="{% url 'notice:list' %}"> Inbox 	{% if unread_count %}
				<span class="badge badge-danger" >{{ unread_count }}</span>
				{% endif %}</a></li>
	




				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
  
					  {{ request.user.username }}
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					  <a class="dropdown-item" href=""><i class="fa fa-cogs fa-fw" aria-hidden="true"></i>&nbsp; My profile</a>
					  <div class="dropdown-divider"></div>
					  <a class="dropdown-item" href=""><i class="fa fa-sign-out fa-fw" aria-hidden="true"></i>&nbsp; logging setting </a>
					</div>
				  </li>
  
  
  
  
				  <li class="nav-item dropdown">
				  
					  <div class="notification">
						  <svg viewbox="0 0 166 197">
							<path d="M82.8652955,196.898522 C97.8853137,196.898522 110.154225,184.733014 110.154225,169.792619 L55.4909279,169.792619 C55.4909279,184.733014 67.8452774,196.898522 82.8652955,196.898522 L82.8652955,196.898522 Z" class="notification--bellClapper"></path>
						  <path d="M146.189736,135.093562 L146.189736,82.040478 C146.189736,52.1121695 125.723173,27.9861651 97.4598237,21.2550099 L97.4598237,14.4635396 C97.4598237,6.74321823 90.6498186,0 82.8530327,0 C75.0440643,0 68.2462416,6.74321823 68.2462416,14.4635396 L68.2462416,21.2550099 C39.9707102,27.9861651 19.5163297,52.1121695 19.5163297,82.040478 L19.5163297,135.093562 L0,154.418491 L0,164.080956 L165.706065,164.080956 L165.706065,154.418491 L146.189736,135.093562 Z" class="notification--bell"></path>
						  </svg>
						  {% if unread_count %}
						<span><a  class="notification--num"href="{% url 'notice:list' %}" >{{ unread_count }}</a></span>  
						  {% endif %}</li>

















			</ul>
		  </div>
		</div>
	</nav>























    <section class="hero section-padding" data-scroll-index="2">
        <div class="container">
            <div class="row">
                <div class="section-head text-center col-sm-12">
                    <h4>Présentation de l'Expert
                           </h4>
                    <h6>Fiche de profil.</h6>
                </div>
          
                <div class="col-lg-5">
                    <div class="hero-img">
                        <img src="{%  static 'collaboration/images/pic03.jpg' %}" alt="">
                    </div>
                </div>

                <div class="col-lg-7">
                    <div class="content">
                     {% for forum in expert %}
                        <h4>{{forum.nom}} {{forum.prenom}}</h4>
                    </br>
                        <span>{{ forum.fonction}}</span>
                 
                        
                        <p>Domaines d'application :  <span>{% for d in forum.domaine.all %} {{ d.name}}, {% endfor %}</span> </p>
                        <p>Disciplines scientifiques : <span>{% for d in forum.interests.all %} {{ d.name}}, {% endfor %}</span> </p>
                        <p>Adresse email de contact : <span>{{forum.adresse_email}}</span> </p>
                        <p>Composante : <span>{{forum.composante }}</span> </p>
                        
                                               
                     

                    </div>
                </div>
                <div class="section-head text-center col-sm-12">
  
		
                    <a href="{% url 'students:collaboration_page' projet.pk %}"  class="butn butn-light mt-30">
                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                        <span>Retour</span>            
                    </a>
                    
                    <a href="{% url 'students:favoris' pk_1=projet.pk  pk_2=forum.pk   %}" class="butn butn-light mt-30">
                        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                        <span>Ajouter aux Favoris</span>            
                    </a>
                
                    <a href="{% url 'students:expert_confirmation'  pk_1=projet.pk  pk_2=forum.pk  %}" class="butn butn-light mt-30">
                        <span class="" aria-hidden="true"></span>
                         <span>Contacter l'expert</span>           
                     </a>
                    </div>




                   {% endfor %}
            </div>
        </div>
    </section>




























			 <!-- =====================================
			 ==== Start Services -->
	 
		




	 
	 

			 <footer class="text-center">
				 <div class="container">
	 
					
					 <p>&copy; copyright: 2020 <a href="https://templated.co/">ERPI (Research team on innovation process)</a>.</p>
	 
				 </div>
			 </footer>
	 
			 <!-- End Footer ====
			 ======================================= -->
	 
	 
	 








































      <!-- /container -->

      <!-- Le javascript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      {% block javascript %}
        <!-- Required by Bootstrap v4 -->
	   
			 <script src="{% static 'acro/js/jquery-3.0.0.min.js' %}"></script>
		<script src="{% static 'acro/js/jquery-migrate-3.0.0.min.js' %}"></script>

		<!-- popper.min -->
		<script src="{% static 'acro/js/popper.min.js' %}"></script>

		<!-- bootstrap -->
		<script src="{% static 'acro/js/bootstrap.min.js' %}"></script>

		<!-- scrollIt -->
		<script src="{% static 'acro/js/scrollIt.min.js' %}"></script>

		<!-- jquery.waypoints.min -->
		<script src="{% static 'acro/js/jquery.waypoints.min.js' %}"></script>

		<!-- jquery.counterup.min -->
		<script src="{% static 'acro/js/jquery.counterup.min.js' %}"></script>

		<!-- owl carousel -->
		<script src="{% static 'acro/js/owl.carousel.min.js' %}"></script>

		<!-- jquery.magnific-popup js -->
		<script src="{% static 'acro/js/jquery.magnific-popup.min.js' %}"></script>

		<!-- stellar js -->
		<script src="{% static 'acro/js/jquery.stellar.min.js' %}"></script>

		<!-- isotope.pkgd.min js -->
		<script src="{% static 'acro/js/isotope.pkgd.min.js' %}"></script>

		<!-- YouTubePopUp.jquery -->
		<script src="{% static 'acro/js/YouTubePopUp.jquery.js' %}"></script>


		<!-- validator js -->
		<script src="{% static 'acro/js/validator.js' %}"></script>

		<!-- custom scripts -->
		<script src="{% static 'acro/js/scripts.js' %}"></script>

	

		
		
	
      {% endblock javascript %}

      {% block modal %}{% endblock modal %}

    {% endblock body %}
  </body>

  <!-- /.container -->
</html>