django_school/classroom/urls.py
from django.urls import include, path

from .views import classroom, students

urlpatterns = [

    
       path('home_page/', students.home_page.as_view(), name='home_page'),
       path('mots_cles/add/', students.SubjectCreateView.as_view(), name='subject_add'),
       path('domaine/add/', students.DomaineCreateView.as_view(), name='domaine_add'),
       path('type/add/', students.TypeCapteurCreateView.as_view(), name='type_add'),
       path('flyer/', students.FlyerView.as_view(), name='flyer'),
       path('profile_detail/<int:pk_1>/<int:pk_2>/', students.StudentListView.as_view(), name='student_profile'),
       path('collaboration/potentielle/<int:pk_1>/profil_projet/<int:pk_2>/', students.Potentielle_profil.as_view(), name='student_profile_projet'),
       path('expert/<int:pk_1>/', students.expert_annuaire.as_view(), name='annuaire_expert'),
       path('pdf/', students.GeneratePdf.as_view()),
       path('subscribe/', students.subscribe, name = 'subscribe'),
       path('confirmation/<int:pk_1>/<int:pk_2>/<int:pk_3>/<int:notice_id>', students.confirmation_projet, name = 'confirmation_projet'),
       path('confirmation/expert/<int:pk_1>/<int:pk_2>/<int:pk_3>/<int:notice_id>', students.confirmation_expert, name = 'confirmation_expert'),
       path('projet/public/detail/<slug:slug>', students.display_detail_public, name='projet_public'),
       path('projet/public/collaboration/<slug:slug>', students.display_detail_public_coll, name='display_detail_public_coll'),
       path('projet/public/collaboration/actu/<slug:slug>', students.display_detail_public_coll_ac, name='display_detail_public_coll_ac'),
       path('capteur/public/detail/<slug:slug>', students.display_detail_capteur_public, name='capteur_public'),
       path('espace/projet/public/detail/<slug:slug>', students.espace_public, name='espace_public'),
       path('espace/capteur/public/detail/<slug:slug>', students.espace_capteur_public, name='espace_capteur_public'),
       path('boite_a_idees', students.index, name='question_an'),
       path('question/<int:qid>/<slug:qslug>', students.viewquestion),
       path('ask-question', students.askquestion, name='ask_question'),
       path('ajax-answer-question', students.ajaxanswerquestion),
       path('CapMat/', include(([
       path('Accueil/', students.AccueilListView.as_view(), name='first_page'),
       path('Profile/', students.profile_view, name='profile'),
       path('Profile_display/', students.profile, name='profile_dispaly'),
       
       

#Partie 2
#===================================<<<<#Projets >>>>===============================



        path('Projet/', students.HomeView.as_view(), name='lanceur_projet_home'),
        path('resultats_page/<int:pk>/', students.ExpertListView.as_view(), name='collaboration_page'),
        #Mesprojets
        path('Projets/', students.MesProjetsView.as_view(), name='mes_projets'),
        #mettre à jour
        path('projet/<int:pk>/', students.QuizUpdateView.as_view(), name='projet_change'),

       #detail projetMesTechnologies_list
        path('projet/detail/<slug:slug>', students.display_detail, name='projet_detail'),








#Partie 3 
#===================================<<<<#Colaborations>>>>===============================


        #collaboration
          path('collaborations/accueil', students.CollobarationListView.as_view(), name='collaborations'),
        #collaboration_potentielle
          path('collaborations/potentielles', students.PotentielleListView.as_view(), name='list_potentielle'),
         #collaboration_actuelle
          path('collaborations/actuelles', students.ActuelleListView.as_view(), name='list_actuelle'),
         #collaboration_contact
          path('collaborations/contact/<int:pk>/', students.sub_projet, name='potentielle_contact'), 
          
          path('chaine_de_Connaissance/<int:pk>/', students.ChaineListView.as_view(), name='chaine'),




#Partie 3 
#===================================<<<<#Technologies>>>>===============================
        #technologies
        path('technologies/Accueil', students.technologieListView.as_view(), name='technologies'),
        #La banque de technologies
        path('Technologies/Accueil/MesTechnologies', students.MesTechnologiesListView, name='MesTechnologies_list'),

        #Capteurs
        path('Capteurs/', students.CapteursView.as_view(), name='capteur_home'),
        path('capteur/ajouter/', students.CapteurCreateView.as_view(), name='capteur_add'),
        path('capteur/<int:pk>/modifier', students.CapteurUpdateView.as_view(), name='capteur_change'),
        path('capteur/<int:pk>/supprimer/', students.CapteurDeleteView.as_view(), name='capteur_delete'),
        path('capteur/detail/<slug:slug>', students.display_detail_capteur, name='capteur_detail'),


#Partie  4
     #Experts
        path('Experts/', students.ExpertsHomeListView.as_view(), name='expert_home'),
        path('Experts/<int:pk_1>/confirmation/<int:pk_2>/', students.sub_createxpert, name='expert_confirmation'),
        path('Collaboration_send/<int:pk_1>/<int:pk_2>/', students.sub_creatcollab, name='sub_creatcollab'),
        path('Experts/Annuaire', students.AnnuaireListView, name='Annuaire'),
        path('Experts/Liste', students.ExpertPotentielleListView.as_view(), name='liste'),
        path('Experts/Favoris/<int:pk_1>/confirmation/<int:pk_2>/', students.favoris, name='favoris'),


        path('free/', students.free, name='free'),




          
        path('equipe/projet/<int:pk>/', students.equipe_definition, name='equipe_projet'),
        path('equipe/projet/change/<int:pk>/', students.equipe_change.as_view(), name='equipe_change'),




      
   

        path('projet/add/', students.QuizCreateView.as_view(), name='projet_add'),
       
        path('projet/<int:pk>/delete/', students.QuizDeleteView.as_view(), name='projet_delete'),
        path('projet/detail/<slug:slug>', students.display_detail, name='projet_detail'),

        path('espace', students.ForumListView, name='forum_list'),
        path('espace/par/<username>/', students.ForumUserListView.as_view(), name='forum-by'),
        path('espace/par/profile/<username>/', students.ProfilUserListView.as_view(), name='forum_by_profile'),
        path('esm/projet/detail/<slug:slug>', students.forum_projet_detail, name='forum_detail'),

        
        #subject 


        #Gestion projet PDF 

        path('projet/pdf/<int:pk>', students.PdfGestionView.as_view(), name='gestionPDF'),

        #Recherche 

        path('expert', students.ExpertsListView, name='experts_list'),
        path('capteur', students.CapteurListView, name='capteurs_list'),
        path('partager/<int:pk>/', students.Publi_projet, name='publi_projet'),
        path('interests/', students.StudentInterestsView.as_view(), name='student_interests'),
        path('', students.QuizListView.as_view(), name='quiz_list'),
        path('mes_projet/', students.QuizMesView.as_view(), name='projet_list'),
        path('taken/', students.TakenQuizListView.as_view(), name='taken_quiz_list'),
        path('quiz/<int:pk>/', students.take_quiz, name='take_quiz'),
        path('_idées/', students.BoiteListView, name='boite_list'),
        path('_idées/form', students.IdeeCreateView.as_view(), name='idee_form'),
        ], 'classroom'), namespace='students')),



#Partie 3 
#===================================<<<<#Boites à idées>>>>===============================
        


]

django_school/django_school/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf.urls.static import static
from classroom.views import classroom, students, teachers
import notifications.urls
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext








    
 
urlpatterns = [
    
 
   
]
   

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




urlpatterns += i18n_patterns (
    path('', classroom.home, name='home'),
    path('Cap-Mat', include('classroom.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', classroom.SignUpView.as_view(), name='signup'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('reset-password', PasswordResetView.as_view(), name='password_reset'),
    path('reset-password/done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-password/confirm/<uidb64>[0-9A-Za-z]+)-<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset-password/complete/', PasswordResetCompleteView.as_view(),name='password_reset_complete'),

    
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_school/notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    #Notification list
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    path('Inbox/', views.CommentNoticeListView_read.as_view(), name='inbox'),

    #Update notification status
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
    path('update/<int:notice_id>', views.CommentNoticeUpdateView.as_view(), name='update_article'),
       #Update notification status
    path('list/notification', views.ExpertNoticeUpdateView.as_view(), name='notification_expert'),
   
]

django_school/classroom/views/classroom.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def home(request):
    if request.user.is_authenticated:
        if request.user.is_student:
            return redirect('students:first_page')
        else:
            return redirect('students:first_page')
            
    return render(request, 'Home_Page/index.html')

django_school/classroom/templates/ask-question.html
{% load static %}
<!doctype html>

<html class="no-js" lang="zxx">

    <head>

    	<!-- Metas -->
        <meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
		<meta name="keywords" content="HTML5 Template Arco onepage themeforest" />
		<meta name="description" content="Arco - Onepage Multi-Purpose HTML5 Template" />
		<meta name="author" content="" />

		<!-- Title  -->
		<title>CAP-MAT</title>

		<!-- Favicon -->
		<link rel="shortcut icon" href="img/favicon.ico" />

		<!-- Google Fonts -->
		<link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Raleway:100,200,300,400,500,600,700,800" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900" rel="stylesheet">

		<!-- Plugins -->
		<link rel="stylesheet" href="{% static 'acro/css/plugins.css'%}" />

        <!-- Core Style Css -->
        <link rel="stylesheet" href="{% static 'acro/css/style.css'%}" />

    </head>

    <body>

    	<!-- =====================================
    	==== Start Loading -->

    	<div class="loading">
    		<div class="text-center middle">
    			<div class="lds-ellipsis"><div></div><div></div><div></div><div></div></div>
    		</div>
    	</div>

    	<!-- End Loading ====
    	======================================= -->

		<!-- =====================================
    	==== Start Navbar -->
		<nav class="navbar navbar-expand-lg">
			<div class="container">

				<h5 style="color: #FFFFFF;">
					<a  href="{% url 'home' %}">Cap-Mat  </a>
				</h5>

			  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			    <span class="icon-bar"><i class="fas fa-bars"></i></span>
			  </button>

			  <!-- navbar links -->
			  <div class="collapse navbar-collapse" id="navbarSupportedContent">
			    <ul class="navbar-nav ml-auto">
			      <li class="nav-item">
			        <a class="nav-link active" href="{% url 'home' %}" style="color: #FFFFFF;">Home</a>
			      </li>
			      <li class="nav-item">
                    <a class="nav-link" href="{% url 'question_an' %}" data-scroll-nav="0">Espace d'Échanges et de Réflexion</a>
                  </li>
			      <li class="nav-item">
			        <a class="nav-link" href="{% url 'students:MesTechnologies_list' %}" >La Banque de technologies</a>

				</li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'students:forum_list' %}" >Projets & Idées</a>
                  </li>

			    </ul>
			  </div>
			</div>
		</nav>

    	<!-- End Navbar ====
    	======================================= -->

		<!-- ====== Header ======  -->
		<section id="home" class="min-header" data-scroll-index="0">

			<div class="v-middle mt-30">
				<div class="container">
					<div class="row">

						<div class="text-center col-md-12">
							<h5>Espace d'Échanges et de Réflexion</h5>
							<a href="{% url 'students:MesTechnologies_list' %}">La Banque de technologies</a>
							<a href="{% url 'students:forum_list' %}">Projets & Idées</a>
						</div>

					</div>
				</div><!-- /row -->
			</div><!-- /container -->
		</section>
		<!-- ====== End Header ======  -->

		<!--====== Blog ======-->
		<section class="blogs section-padding">
			<div class="container">
				<div class="row">

					<div class="col-md-8">
						<div class="posts">




							<div class="comment-form">
								<div class="title-g mb-50">
									<h3>Poser une question</h3>
								</div>













									<form class="" action="ask-question" method="post">
										{% csrf_token %}
										<input type="text" name="title" value="" autocomplete="off" placeholder="What's your question's title?">
										<br><br>
										<textarea name="question" rows="8" cols="80" placeholder="What's your question?"></textarea>
										<br><br>
										<input type="text" name="posted_by" value="" autocomplete="off" placeholder="Enter your name ...">
										<br><br>
										<input type="submit" name="ask" value="Ask Question">
									</form>
									{% if error %}
										<p class="error">{{ error }}</p>
									{% endif %}





















							</div>

						</div>
					</div>

                    <div class="col-md-4">
						<div class="side-bar">
							<div class="widget search">
								<form>
									<input type="search" name="" placeholder="Type here ...">
									<button type="submite"><i class="fa fa-search" aria-hidden="true"></i></button>
								</form>
							</div>

							<div class="widget">
								<div class="widget-title">
									<h6>Poser une question</h6>
								</div>
								<ul>
									<li><a href="{% url 'ask_question' %}">Poser une question</a></li>
								</ul>
							</div>






						</div>
					</div>

				</div>
			</div>
		</section>
		<!--====== End Blog ======-->


        <footer class="text-center">
            <div class="container">


				<p>&copy; 2020 ERPI Laboratory. All Rights Reserved.</p>
				<p>CAPteurs intelligents pour la transformation des MATériaux (des ressources aux produits : CAP-MAT" est cofinancé par l'union européenne dans le cadre opérationnel FEDER-FSE Lorraine et Massif des Vosges 2014-2020</p>

            </div>
        </footer>




        <!-- jQuery -->
		<script src="{% static 'acro/js/jquery-3.0.0.min.js' %}"></script>
		<script src="{% static 'acro/js/jquery-migrate-3.0.0.min.js' %}"></script>

		<!-- popper.min -->
		<script src="{% static 'acro/js/popper.min.js' %}"></script>

	  	<!-- bootstrap -->
		<script src="{% static 'acro/js/bootstrap.min.js' %}"></script>

		<!-- scrollIt -->
		<script src="{% static 'acro/js/scrollIt.min.js' %}"></script>

		<!-- animated.headline -->
		<script src="{% static 'acro/js/animated.headline.js' %}"></script>

		<!-- jquery.waypoints.min -->
		<script src="{% static 'acro/js/jquery.waypoints.min.js' %}"></script>

		<!-- jquery.counterup.min -->
		<script src="{% static 'acro/js/jquery.counterup.min.js' %}"></script>

		<!-- owl carousel -->
		<script src="{% static 'acro/js/owl.carousel.min.js' %}"></script>

		<!-- jquery.magnific-popup js -->
		<script src="{% static 'acro/js/jquery.magnific-popup.min.js' %}"></script>

		<!-- stellar js -->
		<script src="{% static 'acro/js/jquery.stellar.min.js' %}"></script>

      	<!-- isotope.pkgd.min js -->
      	<script src="{% static 'acro/js/isotope.pkgd.min.js' %}"></script>

        <!-- YouTubePopUp.jquery -->
        <script src="{% static 'acro/js/YouTubePopUp.jquery.js' %}"></script>

      	<!-- validator js -->
      	<script src="{% static 'acro/js/validator.js' %}"></script>

      	<!-- custom scripts -->
        <script src="{% static 'acro/js/scripts.js' %}"></script>
        <script type="text/javascript" src="{% static 'qa/js/jquery.js' %}"></script>
        <script type="text/javascript" src="{% static 'qa/js/core.js' %}"></script>
        <script type="text/javascript">
            var csrftoken = getCookie("csrftoken");
        </script>

    </body>
</html>

django_school/classroom/templates/index.html
{% load static %}
<!doctype html>

<html class="no-js" lang="zxx">

    <head>

    	<!-- Metas -->
        <meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
		<meta name="keywords" content="HTML5 Template Arco onepage themeforest" />
		<meta name="description" content="Arco - Onepage Multi-Purpose HTML5 Template" />
		<meta name="author" content="" />

		<!-- Title  -->
		<title>CAP-MAT</title>

		<!-- Favicon -->
		<link rel="shortcut icon" href="img/favicon.ico" />

		<!-- Google Fonts -->
		<link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Raleway:100,200,300,400,500,600,700,800" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900" rel="stylesheet">

		<!-- Plugins -->
		<link rel="stylesheet" href="{% static 'acro/css/plugins.css' %}" />

        <!-- Core Style Css -->
        <link rel="stylesheet" href="{% static 'acro/css/style.css' %}" />

    </head>
    
    <body>

    	<!-- =====================================
    	==== Start Loading -->

    	<div class="loading">
    		<div class="text-center middle">
    			<div class="lds-ellipsis"><div></div><div></div><div></div><div></div></div>
    		</div>
    	</div>
        
    	<!-- End Loading ====
    	======================================= -->

		<!-- =====================================
    	==== Start Navbar -->

		<nav class="navbar navbar-expand-lg">
			<div class="container">

				<h5 style="color: #FFFFFF;">
					<a  href="{% url 'home' %}">Cap-Mat  </a>     
				</h5>

			  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			    <span class="icon-bar"><i class="fas fa-bars"></i></span>
			  </button>

			  <!-- navbar links -->
			  <div class="collapse navbar-collapse" id="navbarSupportedContent">
			    <ul class="navbar-nav ml-auto">
			      <li class="nav-item">
			        <a class="nav-link active" href="{% url 'home' %}" style="color: #FFFFFF;">Home</a>
			      </li>
			      <li class="nav-item">
                    <a class="nav-link" href="{% url 'question_an' %}" data-scroll-nav="0">Espace d'Échanges et de Réflexion</a>
                  </li>
			      <li class="nav-item">
			        <a class="nav-link" href="{% url 'students:MesTechnologies_list' %}" >La Banque de technologies</a>
				
				</li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'students:forum_list' %}" >Projets & Idées</a>
                  </li>
		
			    </ul>
			  </div>
			</div>
		</nav>

    	<!-- End Navbar ====
    	======================================= -->

		<!-- ====== Header ======  -->
		<section id="home" class="min-header" data-scroll-index="0">

			<div class="v-middle mt-30">
				<div class="container">
					<div class="row">

						<div class="text-center col-md-12">
							<h5>Espace d'Échanges et de Réflexion</h5>
							<a href="{% url 'students:MesTechnologies_list' %}">La Banque de technologies</a>
							<a href="{% url 'students:forum_list' %}">Projets & Idées</a>
						</div>

					</div>
				</div><!-- /row -->
			</div><!-- /container -->
		</section>
		<!-- ====== End Header ======  -->

		<!--====== Blog ======-->
		<section class="blogs section-padding">
			<div class="container">
				<div class="row">
					
					<div class="col-md-8">
						<div class="posts">
                            {% for question in questions %}
							<div class="post">
								<div class="post-img">
									<a class="half-width">
										<img src="{% static 'acro/img/question.jpg' %}" alt="">
									</a>
								</div>
								<div class="content text-center">
									<div class="post-meta">
										<div class="post-title">
											<h5>

                                         
												<a href="/question/{{ question.qid }}/{{ question.slug }}">{{ question.question_title }}</a>
											</h5>
										</div>
									
									</div>

									<div class="post-cont">
										<p>{{ question.question_text|truncatechars:300|slice:"-4" }}....</p>
									</div>

								

								</div>
							</div>
                            {% endfor %}




                          
                          












							<div class="pagination">
								<ul>
									<li>
										<a href="#0">First</a>
									</li>
									<li>
										<a href="#0">1</a>
									</li>
									<li>
										<a href="#0">2</a>
									</li>
									<li>
										<a href="#0">last</a>
									</li>
								</ul>
							</div>

						</div>
					</div>

					<div class="col-md-4">
						<div class="side-bar">
							<div class="widget search">
								<form>
									<input type="search" name="" placeholder="Type here ...">
									<button type="submite"><i class="fa fa-search" aria-hidden="true"></i></button>
								</form>
							</div>

							<div class="widget">
								<div class="widget-title">
									<h6>Poser une question</h6>
								</div>
								<ul>
									<li><a href="{% url 'ask_question' %}">Poser une question</a></li>
								</ul>
							</div>

							<div class="widget">
								<div class="widget-title">
									<h6>Les questions les plus récemment </h6>
								</div>
								<ul>
									{% for question in questions %}
									<li><a href="/question/{{ question.qid }}/{{ question.slug }}">{{ question.question_title }}</a></li>
									
								    {% endfor %}
								</ul>
								
							
							</div>

					
					

						</div>
					</div>

				</div>
			</div>
		</section>
		<!--====== End Blog ======-->




		<!-- =====================================
        ==== Start Footer -->

        <footer class="text-center">
            <div class="container">


				<p>&copy; 2020 ERPI Laboratory. All Rights Reserved.</p>
				<p>CAPteurs intelligents pour la transformation des MATériaux (des ressources aux produits : CAP-MAT" est cofinancé par l'union européenne dans le cadre opérationnel FEDER-FSE Lorraine et Massif des Vosges 2014-2020</p>

            </div>
        </footer>

        <!-- End Footer ====
        ======================================= -->



       
        <!-- jQuery -->
		<script src="{% static 'acro/js/jquery-3.0.0.min.js' %}"></script>
		<script src="{% static 'acro/js/jquery-migrate-3.0.0.min.js' %}"></script>

		<!-- popper.min -->
		<script src="{% static 'acro/js/popper.min.js' %}"></script>

	  	<!-- bootstrap -->
		<script src="{% static  'acro/js/bootstrap.min.js' %}"></script>

		<!-- scrollIt -->
		<script src="{% static  'acro/js/scrollIt.min.js' %}"></script>

		<!-- animated.headline -->
		<script src="{% static  'acro/js/animated.headline.js' %}"></script>

		<!-- jquery.waypoints.min -->
		<script src="{% static  'acro/js/jquery.waypoints.min.js' %}"></script>

		<!-- jquery.counterup.min -->
		<script src="{% static  'acro/js/jquery.counterup.min.js' %}"></script>

		<!-- owl carousel -->
		<script src="{% static  'acro/js/owl.carousel.min.js' %}"></script>

		<!-- jquery.magnific-popup js -->
		<script src="{% static  'acro/js/jquery.magnific-popup.min.js' %}"></script>

		<!-- stellar js -->
		<script src="{% static  'acro/js/jquery.stellar.min.js' %}"></script>

      	<!-- isotope.pkgd.min js -->
      	<script src="{% static  'acro/js/isotope.pkgd.min.js' %}"></script>

        <!-- YouTubePopUp.jquery -->
        <script src="{% static  'acro/js/YouTubePopUp.jquery.js' %}"></script>

      	<!-- validator js -->
      	<script src="{% static  'acro/js/validator.js' %}"></script>

      	<!-- custom scripts -->
        <script src="{% static  'acro/js/scripts.js' %}"></script>

    </body>
</html>

django_school/classroom/templates/invoice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django HTMLtoPDF Tutorial</title>
</head>
<body>
    <h1>HTML To PDF</h1>
     <b>I'm building web-based, data-driven apps using Django. <br>
Eventually (or unfortunately), I will need to generate some reports that are printer-friendly. <b>
Logically, PDF is the format for such files... <br>
so how am I going to convert my xHTML and CSS to a nice-looking PDF document?<br>

The Django Book has a whole chapter dedicated to Generating Non-HTML Content.<br> 
They seem to to be fond of ReportLab ToolKit.<br>
 The caveat here, though, is that you need to know a bit about the internals of a PDF document.<br> 
If you're familiar with this, the ReportLab toolkit seems to be the way to go! It has many features, and it seems to be a powerful PDF-generating tool.
</b>
</body>
</html>

django_school/classroom/templates/mail_template.html
{{ request.user.username}}